name = "repo-pulse-lite"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "repo-pulse-lite"

[env.production.vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
GITHUB_REDIRECT_URI = ""

[[env.production.kv_namespaces]]
binding = "REPO_PULSE_KV"
id = ""
preview_id = ""
